language: node_js
node_js:
  - "6"
  - "node"
services:
  - postgresql
before_script:
  - psql -c 'create database lobster;' -U postgres
  - psql -d lobster -a -f ./scripts/create_schema.sql
  - psql -d lobster -a -f ./scripts/seed_db.sql